<a href="https://colab.research.google.com/github/satwikbarik2-hub/Data-preprocessing/blob/main/DataManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=[1,2,3,4,5]
series=pd.Series(data)
print("sseries:\n",series)

sseries:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#create a series from dictionry
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [ ]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
#dataframe
df=pd.read_csv('sales_data.csv')
print(df.head(5))

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal

In [ ]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
data={
    'name':['satwik','john','jack'],
    'age':[25,30,45],
    'city':['bangalore','new york','florida']
}
data

{'name': ['satwik', 'john', 'jack'],
 'age': [25, 30, 45],
 'city': ['bangalore', 'new york', 'florida']}

In [ ]:
df=pd.DataFrame(data)
df

     name  age       city
0  satwik   25  bangalore
1    john   30   new york
2    jack   45    florida

In [ ]:
df['name']

0    satwik
1      john
2      jack
Name: name, dtype: object

In [ ]:
df.loc[0]

name       satwik
age            25
city    bangalore
Name: 0, dtype: object

In [ ]:
df.iloc[0,1]

np.int64(25)

In [ ]:
df.at[2,'age']

np.int64(45)

In [ ]:
df.iat[2,2]

'florida'

In [ ]:
#data manuplatio with dataframe
df['salary']=[50000,60000,70000]

In [ ]:
df

     name  age       city  salary
0  satwik   25  bangalore   50000
1    john   30   new york   60000
2    jack   45    florida   70000

In [ ]:
df.drop('salary',axis=1)

     name  age       city
0  satwik   25  bangalore
1    john   30   new york
2    jack   45    florida

In [ ]:
df.drop('salary',axis=1,inplace=True)

In [ ]:
df

     name  age       city
0  satwik   25  bangalore
1    john   30   new york
2    jack   45    florida

In [ ]:
#add age to column
df['age']=df['age']+1
df

     name  age       city
0  satwik   26  bangalore
1    john   31   new york
2    jack   46    florida

In [ ]:
df.drop(0)
df

     name  age       city
0  satwik   26  bangalore
1    john   31   new york
2    jack   46    florida

In [ ]:
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000